// <auto-generated />
namespace MovieMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IntroducingManyToManyBetweenBillsAndFilms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntroducingManyToManyBetweenBillsAndFilms));
        
        string IMigrationMetadata.Id
        {
            get { return "202012300347409_IntroducingManyToManyBetweenBillsAndFilms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
